name: scale-pt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fabric      # ssh
  - omegaconf   # yaml
  - rich
  - ipykernel
  - ipywidgets
  - pip
  - pip:
    - open3d
    - redis